version: "3"

networks:
  rsspush:
    external: false

services:
  server:
    image: gitea/gitea:1.20.5
    container_name: rsspush
    restart: always
    networks:
      - rsspush
    volumes:
      - ./config/:/app/config/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8003:8000"
    depends_on:
      - db

  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=rsspush
      - POSTGRES_PASSWORD=rsspush
      - POSTGRES_DB=rsspush
    networks:
      - rsspush
    volumes:
      - ./postgres:/var/lib/postgresql/data
